apiVersion: v1
kind: Deployment
metadata:
  name:  postgres
  labels:
    name:  postgres
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:  postgres
    spec:
      containers:
      - image:  postgres:9.6.5
        name:  postgres
        env:
        - name:  POSTGRES_DB
          value: postgres_db
        - name: POSTGRES_USER
          value: user
        - name:  POSTGRES_PASSWORD
          value: password       
        ports:
        - containerPort:  5432
          name:  postgres