apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: 5thcinema/go-backend-services:k8s-interview
        imagePullPolicy: Never
        ports:
        - containerPort:  5555

