apiVersion: v1
kind: Service
metadata:
  name: grafana-renderer-svc
  namespace: monitoring
spec:
  selector:
    app: grafana-image-renderer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP