apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  oidc.config: |
    name: OktaSSO
    issuer: https://kubiya-admin.okta.com/oauth2/default
    clientID: <your-client-id>
    clientSecret: <your-client-secret>
    requestedScopes:
      - openid
      - profile
      - email
    redirectURI: https://argo.demos.kubiya.ai/auth/callback