octopus:
  ingress:
    enabled: true
    spec:
      ingressClassName: inMotionIngress
    tls:
    - hosts:
      - octopus.inmotion.us
      secretName: octopus.inmotion.us
    path: /
    hosts:
      - octopus.inmotion.us
  acceptEula: "Y" # It is required to accept the Octopus EULA https://octopus.com/legal/customer-agreement
  # <generated master key - base64> 
  # echo $(cat octopus-master-key)
  masterKey: PoFvd+w7ZRCrkLkY896F1LyXJLtDxKiY7takhxlr5IAtulj4VoXwLfbBAwt9AhA=
  # Server=tcp:127.0.0.1,5432;Initial Catalog=OctopusDeploy;Persist Security Info=False;User ID=octopus-deploy;Password=h0Sf2rNAjk;Encrypt=True;Connection Timeout=30;
  databaseConnectionString: "Server=tcp:127.0.0.1,5432;Initial Catalog=OctopusDeploy;Persist Security Info=False;User ID=postgres;Password=waftaqt1Jw;Encrypt=True;Connection Timeout=30;" # Server=tcp:octopus-deploy.database.windows.net,1433;Initial Catalog=OctopusDeploy;Persist Security Info=False;User ID=octopus-deploy;Password={your_password};Encrypt=True;Connection Timeout=30;
  # add license key
  # licenseKeyBase64: <your base64 encoded license key>   
  username: admin
  password: password
  packageRepositoryVolume:
    size: 20Gi 
    storageAccessMode: ReadWriteOnce
  artifactVolume:
    size: 1Gi 
    storageAccessMode: ReadWriteOnce
  taskLogVolume: 
    size: 1Gi 
    storageAccessMode: ReadWriteOnce
